version: '3.9'

services:
  # Creates a container/service named db
  db:
    # This downloads and runs Postgres with TimescaleDB
    image: timescale/timescaledb:latest-pg15

    # Pull the following from the .env file
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # Allows the app to be connected with localhost: 5432
    ports:
      - "5432:5432"

    # Allows data to persist in the database even after the container is deleted
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
